import Barcode from "@/components/bardcode";

export const metadata = {
  title: "Barcode Generated",
  description: "Generated by create next app",
};

export default function BarcodePage() {
  return <Barcode />;
}
